<?xml version="1.0"?>
<package format="3">
  <name>low_level</name>
  <version>1.0.0</version>
  <description>ROS 2 low-level joint and gripper controllers for Franka research robots.</description>

  <maintainer email="jaco@todo.todo">jaco</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>controller_interface</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>realtime_tools</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>franka_msgs</depend>
  <depend>franka_semantic_components</depend>

  <exec_depend>controller_manager</exec_depend>
  <exec_depend>controller_manager_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>franka_bringup</exec_depend>
  <exec_depend>franka_gripper</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
